Parameters:
  MyRoleName:
    Type: String

Resources:
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle
  TestRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

Outputs:
  test:
    Value: !Ref MyRoleName
